### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by ASKProducts** [coolstar/RecordMyScreen#13]
Hey I am new to GitHub. I see that some content has been updated on this main project, and I forked it before the edits were made. How do I pull/merge data from this repository into my forked version?

**Comment by coolstar** [comment]
on the copy on your computer go to the folder RecordMyScreen is in the terminal, and use this command: "git pull https://github.com/coolstar/RecordMyScreen.git master" to pull the changes to your local copy and "git push origin master" to put it onto your fork (assuming you cloned from your fork instead of my original)
