### ISSUE TITLE
Crash on Record (iPod Touch)

### ISSUE THREAD

**Issue by princessjinifer** [coolstar/RecordMyScreen#24]
iPod Touch 4th Generation.

The app keeps crashing after hitting the record button while it opens. I emailed one of the developers and they said to post here, and to send them the output of the file "/var/mobile/Library/Logs/CrashReporter/RecordMyScreen-xxx.plist" but when I went to the "/var/mobile/Library/Logs/CrashReporter/" directory, it was not there. The first link is what is inside that directory, the second link is the Syslog from the very first time RecordMyScreen is mentioned to the very last time it is mentioned after trying to run it.

/var/mobile/Library/Logs/CrashReporter/: http://pastebin.com/0Wp17vyU
Syslog: http://pastebin.com/UQ83jEmt

**Comment by coolstar** [comment]
What is SiriEnabler/SiriLocation and why is it being loaded into RecordMyScreen?

**Comment by princessjinifer** [comment]
I installed the Ac!D Siri along with PAT Assistant server to have Siri on my device. I will try running it after disabling Siri. I have no clue why it is being loaded into RecordMyScreen.

**Comment by coolstar** [comment]
About Ac1dSiri: That is Illegal, You Know?
Also, these ways to get Siri from Cydia are all well known to cause problems. Disabling it in settings won't help either. You must uninstall it. Only Spire on 5.0.1 is legal, and all others are illegal. That too, I've had plenty of problems with Spire on my old iPod touch 3G last year. Also, I see a ton of LowMemory plists there. That is most likely Ac1dSiri, as these illegally developed extensions can have plenty of memory leaks, etc. And that's just the start of it.

If you want something like Siri on your iPod touch 4, fine. You can compile VAssistant from my github repo using iphone-gcc on the BigBoss repo and theos from @DHowett's github repo. However, do not, and I repeat DO NOT use any of these illegal ways to get Siri or even Spire if you want stability. And remember the iPod touch 4 has only 256 MB of RAM, which is the lowest for an iOS 6 device already, and these memory leaks from Ac1dSiri and others won't help either. Also, Siri itself is a resource hog, which is why Apple didn't put it on the iPod touch 4.

With that in mind, I now close the issue.
