### ISSUE TITLE
iPad Mini Screen Cut-Off

### ISSUE THREAD

**Issue by PyroFilmsFX** [coolstar/RecordMyScreen#46]
Is there any code to fix the fact that whenever an iPad Mini is recorded the screen is cut off? This is not just me, I signed the app with an enterprise account and released it for other users to use, so far thats the problem

**Comment by tkviper** [comment]
I found a quick fix for the iPad Mini...  you're welcome.

Open up CSScreenRecorder.m and edit the function below..  

You can thank me by visiting my website.. I have some interesting apps myself. Thanks.

Regards,
tkviper
www.tkviper.com
www.wkode.com

#pragma mark - Encoding
- (void)_setupVideoContext
  {
  // Get the screen rect and scale
  CGRect screenRect = [UIScreen mainScreen].bounds;
  float scale = [UIScreen mainScreen].scale;
  
  // Apparently, iPad Mini frame buffer is also Portrait like the iPhone...
  _width = screenRect.size.width \* scale;
  _height = screenRect.size.height \* scale;
  
  /\* I commented out the following section because I only care about the iPad Mini. If you want it to work for all devices, then complete the if-else block below..  iPhone and iPad Mini use the same code... I haven't checked the full sized iPad yet... 
  
  // setup the width and height of the framebuffer for the device
  if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
      // iPhone frame buffer is Portrait
      _width = screenRect.size.width \* scale;
      _height = screenRect.size.height \* scale;
  } else {
      // iPad frame buffer is Landscape
      _width = screenRect.size.height \* scale;
      _height = screenRect.size.width \* scale;
  }
  */

**Comment by coolstar** [comment]
I already have a better way to support all devices without hardcoding anything about the screen. This uses 2 additional private APIs, I'll release the source code for the fix as soon as I fix up some legal stuff going on with the ripoff (xRec).

**Comment by tkviper** [comment]
I look forward to the update. I was frustrated all day like the original poster.. now I'm really loving the app.. I hope this quick fix gives him the same temporary relief. Good job on the project. 
I bought the ripoff xRec app not knowing it was a rip-off of your app. I can tell he just changed the interface a bit... I hope you nailed this loser... xRec is already pulled from the AppStore.... it sucks Apple doesn't refund us on these illegal apps.

**Comment by Rythmere** [comment]
This doesn't help the person opened the issue cant update the app on his website so a lot people can't get the app updated to work on ipad mini

**Comment by Rythmere** [comment]
Tkviper can that be done with iexplorer and if  so can u send me the edited file because I don't understand it?

**Comment by coolstar** [comment]
This has been fixed in the latest binary release on Cydia. Unfortunately I can't update the source code anymore :(
