### ISSUE TITLE
App doesn't play videos recorded during Facetime call

### ISSUE THREAD

**Issue by soylentRus** [coolstar/RecordMyScreen#59]
Hello! I'm using this app on a non-jail broken 8GB 4th gen Touch, and it works great on almost every app in which I've tested it, save Facetime. I begin the recording, leave the app, enter and leave FT then return to the app and stop the recording. When I check on it, it has usually been saved as two files, one .mp4 and one .mov, neither of which are playable when I attempt to do so. All other recordings work fine. I'm a novice, so I certainly may be overlooking something obvious, unless this isn't compatible with FT. Any advice would be greatly appreciated. Thanks for your time!

**Comment by PyroFilmsFX** [comment]
You must wait at least 30-60 seconds after you stop the recording to allow the video and audio to merge properly.

**Comment by soylentRus** [comment]
Hmm I tried that, but it doesn't seem to work either. If I come out of FT and reopen RMS, it crashes the app and ends the FT call in exactly 5 seconds if I don't push stop before then. If I do push stop and wait, the video and audio seem to be merged (one .mp4 file), but it still won't play. I can show you the crash report if that would help.

**Comment by coolstar** [comment]
This isn't an issue with RecordMyScreen. The issue is the iPod touch 4 doesn't have enough RAM to capture screen buffers (RecordMyScreen), capture images from the webcam (facetime), encode video (recordmyscreen and facetime), stream video (facetime), and decode video (facetime). iOS is actually force-quitting either RecordMyScreen or Facetime, as it runs out of memory. It doesn't seem to crash on my iPod 5 as it has more RAM, however it does get a bit slow even with the A5 chip with both running.
