### ISSUE TITLE
What do i do?

### ISSUE THREAD

**Issue by DigitalGaming** [coolstar/RecordMyScreen#66]
you told me to update it but i dont know what i need to change, if you tell me ill gladly do it for you.

**Comment by gg4u** [comment]
Hi coolstar!!
thank you already for your reply!
I installed it on ipad2 mini - iOS6, succeful.
Screen recording works, but it record only a cropped square instead of the whole screen, no matter if landscape or portait setting is chosen.

Instead, I haven't succeed on iOS7, ipad4 (retina)
Still to try on iphone 5s - i wlll let you know :)

It would be cool if, beyond fixing the squared cropped area, it would also work on iOS7.
An improvement would be to let the app start record after a delay, so that you could record only a part of the interaction fo the screen, and skipping the recording of closing your app.

**Comment by coolstar** [comment]
It was a rhetorical question...

**Comment by gg4u** [comment]
i am sorry, I asked you for your avalaibility and proposed a possibility of
a budget for your time.
I was not rhetorical and did not mean to offend you.

On Tue, Dec 17, 2013 at 1:55 AM, coolstar notifications@github.com wrote:

> Closed #66 https://github.com/coolstar/RecordMyScreen/issues/66.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/coolstar/RecordMyScreen/issues/66
> .

## 

Luigi Assom

Skype contact: oggigigi
